on:
  workflow_dispatch:
    inputs:
      port_payload:
        required: true
        description: "Port's payload, including details for who triggered the action and general context (blueprint, run id, etc...)"
        type: string
    secrets: 
      ORG_TOKEN: 
        required: true
      PORT_CLIENT_ID:
        required: true
      PORT_CLIENT_SECRET:
        required: true
jobs: 
  scaffold:
    runs-on: ubuntu-latest
    steps:
      - run: |
          python3 -m pip install --user cookiecutter           
      - run: |
          access_token=$(curl --location --request POST 'https://api.getport.io/v1/auth/access_token' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "clientId": "${{ secrets.PORT_CLIENT_ID }}",
              "clientSecret": "${{ secrets.PORT_CLIENT_SECRET }}"
          }' | jq '.accessToken' | sed 's/"//g')        
          curl --location "https://api.getport.io/v1/actions/runs/${{ fromJson(inputs.port_payload).context.runId }}/logs" \
          --header "Authorization: Bearer $access_token" \
          --header "Content-Type: application/json" \
          --data "{
            \"message\": \"🚀 Creating a new repository: ${{ fromJson(inputs.port_payload).payload.properties.name }}  \"
          }"
      - uses: actions/checkout@v3
      - uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: UPSERT
          identifier: ${{ fromJson(inputs.port_payload).payload.properties.name }}
          title: ${{ fromJson(inputs.port_payload).payload.properties.name }}
          blueprint: microservice
          runId:  ${{ fromJson(inputs.port_payload).context.runId }}
          properties: |
            {
              "description": "${{ fromJson(inputs.port_payload).payload.properties.description }}"
            }
          team: '["${{ fromJson(inputs.port_payload).payload.properties.team }}"]'
      - uses: howlowck/create-repo-action@v1.0
        with:
          repoOrg: 'port-cookiecutter-example'
          repoName: ${{ fromJson(inputs.port_payload).payload.properties.name }}
          repoVisibility: 'private'
          securityToken: ${{ secrets.ORG_TOKEN }}
      - run: |
          access_token=$(curl --location --request POST 'https://api.getport.io/v1/auth/access_token' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "clientId": "${{ secrets.PORT_CLIENT_ID }}",
              "clientSecret": "${{ secrets.PORT_CLIENT_SECRET }}"
          }' | jq '.accessToken' | sed 's/"//g')        
          curl --location "https://api.getport.io/v1/actions/runs/${{ fromJson(inputs.port_payload).context.runId }}/logs" \
          --header "Authorization: Bearer $access_token" \
          --header "Content-Type: application/json" \
          --data "{
            \"message\": \"🚀 Scaffolding new service using CookieCutter with the template: ${{ fromJson(inputs.port_payload).payload.properties.template }} \"
          }"

      - run: |
          git clone https://oauth2:${{ secrets.ORG_TOKEN }}@github.com/port-cookiecutter-example/${{ fromJson(inputs.port_payload).payload.properties.name }}.git cloned_repo
          cd cloned_repo
          if [ "${{ fromJson(inputs.port_payload).payload.properties.template }}" = "Django" ]; then
            cookiecutter https://github.com/agconti/cookiecutter-django-rest.git
          fi

          if [ "${{ fromJson(inputs.port_payload).payload.properties.template }}" = "Flask" ]; then
            cookiecutter https://github.com/cookiecutter-flask/cookiecutter-flask.git
          fi

          if [ "${{ fromJson(inputs.port_payload).payload.properties.template }}" = "FastAPI" ]; then
            cookiecutter https://github.com/tiangolo/full-stack-fastapi-postgresql.git
          fi

          if [ "${{ fromJson(inputs.port_payload).payload.properties.template }}" = "NodeJS" ]; then
            cookiecutter https://github.com/rrwen/cookiecutter-npm.git
          fi

          if [ "${{ fromJson(inputs.port_payload).payload.properties.template }}" = "Go" ]; then
            cookiecutter https://github.com/lacion/cookiecutter-golang.git
          fi
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Initial commit after scaffolding"
          git push

      - run: |
          access_token=$(curl --location --request POST 'https://api.getport.io/v1/auth/access_token' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "clientId": "${{ secrets.PORT_CLIENT_ID }}",
              "clientSecret": "${{ secrets.PORT_CLIENT_SECRET }}"
          }' | jq '.accessToken' | sed 's/"//g')        
          curl --location "https://api.getport.io/v1/actions/runs/${{ fromJson(inputs.port_payload).context.runId }}/logs" \
          --header "Authorization: Bearer $access_token" \
          --header "Content-Type: application/json" \
          --data "{
            \"message\": \"✅ Done scaffolding repository: ${{ fromJson(inputs.port_payload).payload.properties.name }} with template ${{ fromJson(inputs.port_payload).payload.properties.template }}\"
          }"          